@host_address = http://localhost:5039

###
GET {{host_address}}/

###
@email = tom.krasienko@gmail.com
@password = TomaszK123!

###
# @name sign_up
POST {{host_address}}/users-module/users
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "firstName": "Tom",
  "lastName": "Krasienko"
}

###
@user_id = {{sign_up.response.headers.x-resource-id}}

###
# @name sign_in
POST {{host_address}}/users-module/users/tokens
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
GET {{host_address}}/users-module/users/{{user_id}}
Authorization: bearer {{token}}

###
@token = {{sign_in.response.body.$.token}}

###
POST {{host_address}}/users-module/users/subscription-order
Authorization: bearer {{token}}
Content-Type: application/json

{
  "userId": {
    "value": "01JDC7WJ7XTCR7YEEX81RJMSJE"
  },
  "subscriptionId": {
    "value": "01JDEMJMBP7DMM3GMNWCE62FS2"
  }
}

###
# @name create_activity_rule
POST {{host_address}}/api/activity-rules-module/activity-rules
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "details": {
      "title": "rule 3 first day",
      "note": "string"
    },
  "mode": "FirstDayOfWeek",
  "selectedDays":null
}

###
@activity_rule_id = {{create_activity_rule.response.headers.headers.x-resource-id}}

###
# @name create_activity_from_rule
POST {{host_address}}/api/daily-trackers-module/daily-trackers/activities/{{activity_rule_id}}
Authorization: Bearer {{token}}

@activity_id_from_rule = {{create_activity_from_rule.response.headers.x-resource-id}}

###
# @name create_activity
POST {{host_address}}/api/daily-trackers-module/daily-trackers/activities
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "day": "2025-01-04",
  "details": {
    "title": "string",
    "note": "string"
  },
  "stages": [
    {
    "title": "string",
    "index": 1
    }
  ]
}

###
@activity_id = {{create_activity.response.headers.x-resource-id}}

###
GET {{host_address}}/api/daily-trackers-module/daily-trackers/activities/{{activity_id}}
Authorization: Bearer {{token}}

###
GET {{host_address}}/activity-rules-module/activity-rules-internal/modes/07-01-2025