@host_address = http://localhost:5039

###
GET {{host_address}}/

###
@email = tom.krasienko@gmail.com
@password = TomaszK123!

###
POST {{host_address}}/users/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "firstName": "Tom",
  "lastName": "Krasienko"
}
