# @url = http://localhost:6001
@url = http://localhost:5097

@email = tom.krasienko@gmail.com
@password = TomaszK123!

###
POST {{url}}/users/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "firstName": "Tom",
  "lastName": "Krasienko"
}

###
# @name sign_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###
@token = {{sign_in.response.body.$.token}}

###
GET {{url}}/users/subscriptions
Authorization: bearer {{token}}

###
POST {{url}}/activity-rules/create
Authorization: bearer {{token}}
Content-Type: application/json

{
  "title": "test",
  "mode": "EveryDay"
}

###
GET {{url}}/activity-rules
Authorization: bearer {{token}}