// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discipline.application.Infrastructure.DAL;

#nullable disable

namespace discipline.application.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(DisciplineDbContext))]
    [Migration("20240621145712_initial_migrations")]
    partial class initial_migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("discipline.application.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DailyProductivityDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsChecked")
                        .HasMaxLength(100)
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyProductivityDay");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("discipline.application.Domain.Entities.ActivityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedDays")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("ActivityRules");
                });

            modelBuilder.Entity("discipline.application.Domain.Entities.DailyProductivity", b =>
                {
                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Day");

                    b.HasIndex("Day")
                        .IsUnique();

                    b.ToTable("DailyProductivity");
                });

            modelBuilder.Entity("discipline.application.Domain.Entities.Activity", b =>
                {
                    b.HasOne("discipline.application.Domain.Entities.DailyProductivity", null)
                        .WithMany("Activities")
                        .HasForeignKey("DailyProductivityDay");
                });

            modelBuilder.Entity("discipline.application.Domain.Entities.DailyProductivity", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
